# baseURL: "https://bchateli.github.io" 
baseURL: "https://baptistechatelier.com" 
title: Baptiste CHATELIER
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1

        - name: Talks
          url: /talks/
          weights: 2

        - name: Alumni
          url: /alumni/
          weights: 10

        # - name: Search
        #   url: /search/
        #   weights: 10

params:
    description: "Baptiste CHATELIER's personal website."
    author: Baptiste CHATELIER
    googleAnalyticsID: "G-BRN5NB7FFB"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Baptiste CHATELIER
          subtitle: "I am a PhD canditate with the National Institute of Applied Sciences in Rennes, France [(_INSA Rennes_)](https://www.insa-rennes.fr/graduate-school-of-engineering.html) and Mitsubishi Electric R&D Centre Europe [(_MERCE_)](https://www.mitsubishielectric-rce.eu/). My supervisors are [__Luc Le MAGOAROU__](https://luclemagoarou.netlify.app/), [__Vincent CORLAY__](https://www.linkedin.com/in/vincent-corlay-b48001108/) and [__Matthieu CRUSSIERE__](https://www.linkedin.com/in/matthieu-crussiere-06646933/). My research interests include signal processing, applied mathematics and machine learning for wireless communication systems."
          # imageUrl: "avatar.jpg"
          imageUrl: "avatar_new_cropped.png"
          # imageWidth: 154 
          # imageHeight: 205
          imageWidth: 180
          imageHeight: 180
          imageTitle: Baptiste CHATELIER
          buttons:
            - name: Papers
              url: papers/
              weight: 1
            - name: Talks
              url: talks/
              weight: 2
            - name: Alumni
              url: alumni/
              weight: 3
            - name: Search  
              url: search/  
              weight: 4
    socialIcons:
        - name: Email
          url: mailto:baptiste.chatelier@insa-rennes.fr
        # - name: CV
        #   url: CV.pdf
        - name: Linkedin
          url: https://www.linkedin.com/in/baptiste-chatelier/
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=fr&user=HIUZ-UkAAAAJ
        - name: GitHub
          url: https://github.com/bchateli

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Baptiste CHATELIER"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

outputs:
     home:
         - HTML
         - RSS
         - JSON
